pdo_informix.lo: /home/damaleda/Escritorio/Archivos/descargas_Informix/PDO_INFORMIX-1.3.3/pdo_informix.c
	$(LIBTOOL) --mode=compile $(CC) -I/usr/include/php/ext -I. -I/home/damaleda/Escritorio/Archivos/descargas_Informix/PDO_INFORMIX-1.3.3 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/damaleda/Escritorio/Archivos/descargas_Informix/PDO_INFORMIX-1.3.3/pdo_informix.c -o pdo_informix.lo 
informix_driver.lo: /home/damaleda/Escritorio/Archivos/descargas_Informix/PDO_INFORMIX-1.3.3/informix_driver.c
	$(LIBTOOL) --mode=compile $(CC) -I/usr/include/php/ext -I. -I/home/damaleda/Escritorio/Archivos/descargas_Informix/PDO_INFORMIX-1.3.3 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/damaleda/Escritorio/Archivos/descargas_Informix/PDO_INFORMIX-1.3.3/informix_driver.c -o informix_driver.lo 
informix_statement.lo: /home/damaleda/Escritorio/Archivos/descargas_Informix/PDO_INFORMIX-1.3.3/informix_statement.c
	$(LIBTOOL) --mode=compile $(CC) -I/usr/include/php/ext -I. -I/home/damaleda/Escritorio/Archivos/descargas_Informix/PDO_INFORMIX-1.3.3 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/damaleda/Escritorio/Archivos/descargas_Informix/PDO_INFORMIX-1.3.3/informix_statement.c -o informix_statement.lo 
$(phplibdir)/pdo_informix.la: ./pdo_informix.la
	$(LIBTOOL) --mode=install cp ./pdo_informix.la $(phplibdir)

./pdo_informix.la: $(shared_objects_pdo_informix) $(PDO_INFORMIX_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS)  -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_pdo_informix) $(PDO_INFORMIX_SHARED_LIBADD)

